version: '3'

services:
  web:
    build: .
    command: /bin/sh -c "while ! nc -z db 5432; do sleep 2; done; ./entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - DATABASE_NAME=Referral_DB
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      
    depends_on:
      - db
    

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: Referral_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"