# Generated by Django 5.1.3 on 2024-12-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorization', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
